'use client';

import { useState } from 'react';
import { SkillTreeGenerator } from '@/components/skill-tree-generator';
import { Sparkles, Target, TrendingUp, Award } from 'lucide-react';

interface SkillData {
  name: string;
  description: string;
  category: string;
  estimatedHours: number;
  xpReward: number;
}

interface GeneratedTree {
  treeName: string;
  description: string;
  domain: string;
  estimatedDuration: string;
  skills: SkillData[];
}

export default function Home() {
  const [generatedTree, setGeneratedTree] = useState<GeneratedTree | null>(null);

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        {!generatedTree ? (
          <div className="space-y-8">
            {/* Hero Section */}
            <div className="text-center space-y-3 max-w-3xl mx-auto">
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight">
                Level Up Your Skills
                <br />
                <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                  Like a Game
                </span>
              </h1>
              <p className="text-lg text-muted-foreground">
                Transform your learning journey into an interactive skill tree.
                Track progress, earn XP, and unlock achievements.
              </p>
            </div>

            {/* Features */}
            <div className="grid md:grid-cols-3 gap-4 max-w-4xl mx-auto">
              <div className="bg-white p-4 rounded-lg border shadow-sm">
                <Target className="h-8 w-8 text-blue-600 mb-3" />
                <h3 className="font-semibold text-sm mb-1">AI-Powered Paths</h3>
                <p className="text-xs text-muted-foreground">
                  Get personalized learning paths generated by advanced AI
                </p>
              </div>
              <div className="bg-white p-4 rounded-lg border shadow-sm">
                <TrendingUp className="h-8 w-8 text-purple-600 mb-3" />
                <h3 className="font-semibold text-sm mb-1">Track Progress</h3>
                <p className="text-xs text-muted-foreground">
                  Visualize your growth with interactive skill trees
                </p>
              </div>
              <div className="bg-white p-4 rounded-lg border shadow-sm">
                <Award className="h-8 w-8 text-yellow-600 mb-3" />
                <h3 className="font-semibold text-sm mb-1">Earn Rewards</h3>
                <p className="text-xs text-muted-foreground">
                  Unlock achievements and level up as you learn
                </p>
              </div>
            </div>

            {/* Generator Form */}
            <div className="flex justify-center">
              <SkillTreeGenerator onTreeGenerated={setGeneratedTree} />
            </div>
          </div>
        ) : (
          <div className="max-w-4xl mx-auto">
            <div className="bg-white p-8 rounded-lg border shadow-lg">
              <h2 className="text-3xl font-bold mb-4">{generatedTree.treeName}</h2>
              <p className="text-muted-foreground mb-6">{generatedTree.description}</p>

              <div className="space-y-4">
                <div className="flex gap-4">
                  <div className="bg-blue-50 px-4 py-2 rounded-md">
                    <div className="text-sm text-muted-foreground">Domain</div>
                    <div className="font-semibold text-blue-600">{generatedTree.domain}</div>
                  </div>
                  <div className="bg-purple-50 px-4 py-2 rounded-md">
                    <div className="text-sm text-muted-foreground">Duration</div>
                    <div className="font-semibold text-purple-600">{generatedTree.estimatedDuration}</div>
                  </div>
                  <div className="bg-yellow-50 px-4 py-2 rounded-md">
                    <div className="text-sm text-muted-foreground">Skills</div>
                    <div className="font-semibold text-yellow-600">{generatedTree.skills.length}</div>
                  </div>
                </div>

                <div className="mt-8">
                  <h3 className="text-xl font-semibold mb-4">Your Learning Path</h3>
                  <div className="space-y-3">
                    {generatedTree.skills.map((skill, index) => (
                      <div key={index} className="border rounded-lg p-4 hover:border-blue-500 transition-colors">
                        <div className="flex items-start justify-between">
                          <div className="flex-1">
                            <h4 className="font-semibold">{skill.name}</h4>
                            <p className="text-sm text-muted-foreground mt-1">{skill.description}</p>
                            <div className="flex gap-2 mt-2">
                              <span className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded">
                                {skill.category}
                              </span>
                              <span className="text-xs bg-purple-100 text-purple-700 px-2 py-1 rounded">
                                {skill.estimatedHours}h
                              </span>
                              <span className="text-xs bg-yellow-100 text-yellow-700 px-2 py-1 rounded">
                                {skill.xpReward} XP
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <button
                  onClick={() => setGeneratedTree(null)}
                  className="mt-6 text-sm text-muted-foreground hover:text-foreground"
                >
                  ← Create another skill tree
                </button>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t mt-12 py-6">
        <div className="container mx-auto px-4 text-center text-xs text-muted-foreground">
          <p>Built with Next.js, Prisma, and Claude AI</p>
        </div>
      </footer>
    </div>
  );
}
